#define SND_NOTHING 0
#define SND_WOOD_1 1
#define SND_WOOD_2 2
#define SND_WOOD_3 3
#define SND_WALL_1 4
#define SND_WALL_2 5
#define SND_METAL_1 6
#define SND_METAL_2 7
#define SND_PLAST_1 8
#define SND_PLAST_2 9
#define SND_PLAST_3 10
#define SND_CERAM_1 11
#define SND_CERAM_2 12
#define SND_CERAM_3 13
#define SND_SM_BELL 14
#define SND_SM_RING 15
#define SND_LG_BELL 16
#define SND_LG_RING 17
#define SND_MAX 18
