#define MAT_NOTHING 0
#define MAT_WOOD_1 1
#define MAT_WOOD_2 2
#define MAT_WOOD_3 3
#define MAT_WALL_1 4
#define MAT_WALL_2 5
#define MAT_METAL_1 6
#define MAT_METAL_2 7
#define MAT_PLAST_1 8
#define MAT_PLAST_2 9
#define MAT_PLAST_3 10
#define MAT_CERAM_1 11
#define MAT_CERAM_2 12
#define MAT_CERAM_3 13
#define MAT_SM_BELL 14
#define MAT_LG_BELL 15
#define MAT_MAX 16
